### ISSUE TITLE
When iterating through items, mixed-case keys are skipped

### ISSUE THREAD

**Issue by monarialx** [Ayesh/case-insensitive-array#1]
Looping through the items using `valid()`, `current()` and `next()`, mixed-case items are skipped due to a flaw in `valid()` function. When checking if the container key is set (row 78 of Strict.php), `$key` is used instead of `$this->getHash($key)`.
Row 78 should be: `return isset($this->container[$this->getHash($key)][0]);`

**Comment by Ayesh** [comment]
Hi @monarialx  - Thanks a lot for submitting this. You are right indeed there was a bug in the `valid()` method. I just released version 1.0.6 with this fix and some minor improvements.
